#!/bin/bash

# --------------------------------------------------------------------------
# Arquivo de instalação do riso e do risos
# --------------------------------------------------------------------------

dep_cli="avahi-utils rtorrent screen ntfsprogs dialog ssh"
dep_ser="avahi-utils avahi-daemon bittorrent rtorrent screen ntfsprogs ssh dialog"

menu() {
	opcao=$( dialog --stdout \
	--title	'Instalação do RISO' \
	--ok-label 'Confirmar'   \
	--checklist 'Deseja instalar:' \
	0 0 0 \
	RISOS '' ON  \
	RISO '' ON )

	# De acordo com a opção escolhida, executa funcoes
	case $opcao in
		'"RISOS"') instala_risos;;
		'"RISO"') instala_riso;;
		'"RISOS" "RISO"') instala_riso; instala_risos;;
	esac
}

instala_riso() {
    echo "Instalando Cliente (RISO)..."
    
    echo "Baixando dependências..."
    apt-get install -y $dep_cli
    
    echo "Criando árvore de diretórios..."
    mkdir -p /usr/riso
    mkdir -p /usr/riso/imagens
    
    echo "Criando arquivo de inicialização..."
    echo '#!/bin/bash' > /usr/bin/riso
    echo '/usr/riso/riso $@' >> /usr/bin/riso
    chmod +x /usr/bin/riso
    
    echo "Movendo script..."
    cp ./src/riso /usr/riso/riso
    chmod +x /usr/riso/riso
    
    echo "Sistema instalado com sucesso."
    echo "Tente digitar 'riso' para iniciar."
}

instala_risos() {
    echo "Instalando Servidor (RISOS)..."
    
    echo "Criando senha para o root..."
    passwd root
    
    echo "Baixando dependências..."
    apt-get install -y $dep_ser
    
    echo "Criando árvore de diretórios..."
    mkdir -p /usr/riso
    mkdir -p /usr/riso/imagens
    
    echo "Criando arquivo de inicialização..."
    echo '#!/bin/bash' > /usr/bin/risos
    echo '/usr/riso/risos $@' >> /usr/bin/risos
    chmod +x /usr/bin/risos
    
    echo "Movendo script..."
    cp ./src/risos /usr/riso/risos
    chmod +x /usr/riso/risos
    
    echo "Gerando chaves rsa..."
    ssh-keygen -t 'rsa' -f '/root/.ssh/id_rsa' -N ''
    su -c "cat /root/.ssh/id_rsa.pub >> /root/.ssh/authorized_keys2"
    
    echo "Criando arquivo de configuração..."
    echo -n "Qual a partição em que o sistema de recuperação foi instalado(Ex: /dev/sda4):"
    read partrec
    echo -n "Qual a partição em que o Windows foi instalado(Ex: /dev/sda1):"
    read partwindows    
    echo -n "Qual a partição em que o Linux foi instalado(Ex: /dev/sda2):"
    read partlinux
    echo -n "Qual a partição em que o área de troca(swap) foi instalado(Ex: /dev/sda3):"
    read partswap
    echo '<?xml version="1.0" standalone="no"?><!--*-nxml-*-->' > /etc/avahi/services/riso.service
    echo '<!DOCTYPE service-group SYSTEM "avahi-service.dtd">' >> /etc/avahi/services/riso.service
    echo '' >> /etc/avahi/services/riso.service
    echo '<!--riso.service -->' >> /etc/avahi/services/riso.service
    echo '' >> /etc/avahi/services/riso.service
    echo '<!--' >> /etc/avahi/services/riso.service
    echo '  Arquivo com as variáveis de configuração do riso.' >> /etc/avahi/services/riso.service
    echo '  Essas variáveis são usadas para efetuar a comunicação do servidor riso(risos) com os cliente(riso).' >> /etc/avahi/services/riso.service
    echo '  Para mais informações sobre o processo ver http://avahi.org' >> /etc/avahi/services/riso.service
    echo '-->' >> /etc/avahi/services/riso.service
    echo '' >> /etc/avahi/services/riso.service
    echo '<service-group>' >> /etc/avahi/services/riso.service
    echo '  <name>Servidor RISO</name>' >> /etc/avahi/services/riso.service
    echo '' >> /etc/avahi/services/riso.service
    echo '  <service>' >> /etc/avahi/services/riso.service
    echo '    <!--Nome do serviço-->' >> /etc/avahi/services/riso.service
    echo "    <type>_RISO._tcp</type>" >> /etc/avahi/services/riso.service
    echo '' >> /etc/avahi/services/riso.service
    echo '    <!--Campo não é usado-->' >> /etc/avahi/services/riso.service
    echo '    <port>1234</port>' >> /etc/avahi/services/riso.service
    echo '' >> /etc/avahi/services/riso.service
    echo '    <!--Variáveis com tamanho das imagens geradas no servidor-->' >> /etc/avahi/services/riso.service
    echo '    <txt-record>tamlinux=123456789</txt-record>' >> /etc/avahi/services/riso.service
    echo '    <txt-record>tamwindows=123456789</txt-record>' >> /etc/avahi/services/riso.service
    echo '' >> /etc/avahi/services/riso.service
    echo '    <!--Localização dos sistemas operacionais no HD-->' >> /etc/avahi/services/riso.service
    echo "    <txt-record>partswap=${partswap}</txt-record>" >> /etc/avahi/services/riso.service
    echo "    <txt-record>partrec=${partrec}</txt-record>" >> /etc/avahi/services/riso.service
    echo "    <txt-record>partlinux=${partlinux}</txt-record>" >> /etc/avahi/services/riso.service
    echo "    <txt-record>partwindows=${partwindows}</txt-record>" >> /etc/avahi/services/riso.service
    echo '' >> /etc/avahi/services/riso.service
    echo '  </service>' >> /etc/avahi/services/riso.service
    echo '</service-group>' >> /etc/avahi/services/riso.service
    
    
    echo "Sistema instalado com sucesso"
    echo "Tente risos para iniciar"
}



#Verifica se usuário é o root antes de executar.
USER=`id -u`
if [ $USER == '0' ]; then
    menu
else
    echo "Só o root pode fazer isso, jovenzinho!"
fi
